GOBIN = $(shell go env GOPATH)/bin

include .env
export

all: run
.PHONY: all

run: 
	@go run cmd/server/main.go 
.PHONY: run

build: test
	@go build cmd/server/main.go 
.PHONY: build

test: 
	@go test -v ./...
.PHONY: test