GOBIN = $(shell go env GOPATH)/bin

include .env
export

all: run
.PHONY: all

run: 
	@go run cmd/gateway/main.go 
.PHONY: run

install:
	@go build -o {{ .PluginConfig.PluginName }}
	@mv {{ .PluginConfig.PluginName }} ${GOBIN}
.PHONY: install

build: test
	@go build cmd/gateway/main.go 
.PHONY: build

test: 
	@go test -v ./...
.PHONY: test